[package]
name = "metazap"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
image = "0.25"
walkdir = "2.5"
anyhow = "1.0"  # For easy error handling
